# Generated by Django 5.2 on 2025-04-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('votes', models.IntegerField()),
                ('growth', models.FloatField()),
                ('logo_url', models.URLField()),
                ('product_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
